CREATE TABLE `company_kkd_deposit_item` (
	`Id` BIGINT(16) NOT NULL AUTO_INCREMENT,
	`CompanyCode` VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8_bin',
	`ItemCode` VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8_bin',
	`ItemName` VARCHAR(256) NOT NULL DEFAULT '' COLLATE 'utf8_bin',
	`IsKkd` SMALLINT(1) NOT NULL DEFAULT '0',
	`IsDeposit` SMALLINT(1) NOT NULL DEFAULT '0',
	`InsertDateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`InsertUser` VARCHAR(256) NULL DEFAULT '' COLLATE 'utf8_bin',
	`UpdateDateTime` DATETIME NULL DEFAULT NULL,
	`UpdateUser` VARCHAR(256) NULL DEFAULT '' COLLATE 'utf8_bin',
	`Deleted` SMALLINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;
