CREATE TABLE `visitor_visit_kkd_deposit_item` (
	`Id` BIGINT(16) NOT NULL AUTO_INCREMENT,
	`CompanyCode` VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8_bin',
	`VisitId` BIGINT(16) NOT NULL DEFAULT '0',
	`VisitorCode` VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8_bin',
	`ItemCode` VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8_bin',
	`Quantity` INT(11) NOT NULL DEFAULT '0',
	`ItemDesc` VARCHAR(256) NOT NULL DEFAULT '' COLLATE 'utf8_bin',
	`IsKkd` SMALLINT(1) NOT NULL DEFAULT '0',
	`IsDeposit` SMALLINT(1) NOT NULL DEFAULT '0',
	`ReturnDesc` VARCHAR(1024) NOT NULL DEFAULT '' COLLATE 'utf8_bin',
	`ReturnState` SMALLINT(6) NOT NULL DEFAULT '0',
	`InsertDateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`InsertUser` VARCHAR(128) NULL DEFAULT '' COLLATE 'utf8_bin',
	`UpdateDateTime` DATETIME NULL DEFAULT NULL,
	`UpdateUser` VARCHAR(128) NULL DEFAULT '' COLLATE 'utf8_bin',
	`Deleted` SMALLINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;
