-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.32-0ubuntu0.18.04.1 - (Ubuntu)
-- Server OS:                    Linux
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping data for table vpcontract_dev.work_permit_question: ~148 rows (approximately)
/*!40000 ALTER TABLE `work_permit_question` DISABLE KEYS */;
INSERT INTO `work_permit_question` (`Id`, `CompanyCode`, `QuestionCode`, `Question`, `Deleted`) VALUES
	(2, 'PLADIS', 'PLADIS_Q1', 'Gıda güvenliği riski var mıdır?', 0),
	(3, 'PLADIS', 'PLADIS_Q2', 'Çalışan işe göre kullanılması gereken kişisel koruyucu donanımı takıyor mu?', 0),
	(4, 'PLADIS', 'PLADIS_Q3', 'Çalışma yapılan alan düzenli mi?', 0),
	(5, 'PLADIS', 'PLADIS_Q4', 'Üretim sahası kurallarına uygun hareket ediyor mu? (yeme içme, el dezenfeksiyonu, ürüne temas vb.)', 0),
	(6, 'PLADIS', 'PLADIS_Q5', 'Çalışma alanında ürünlere fiziksel kontaminasyon riski var mı?', 0),
	(7, 'PLADIS', 'PLADIS_Q6', 'Çalışma alanında ürünlere kimyasal kontaminasyon riski var mı?', 0),
	(8, 'PLADIS', 'PLADIS_Q7', 'Çalışma alanında ürünlere biyolojik kontaminasyon riski var mı?', 0),
	(9, 'PLADIS', 'PLADIS_Q8', 'Çalışma alanında ürünlere radyolojik kontaminasyon riski var mı?', 0),
	(10, 'PLADIS', 'PLADIS_Q9', 'Çalıştığı alanda kullandığı kimyasalların MSDSi var mı? Gıdaya temas eden kimyasal kullanıyor mu? Kullanılan kimyasalın gıdaya uygunluk belgesi var mı?', 0),
	(11, 'PLADIS', 'PLADIS_Q10', 'Çalışma alanında alerjen riski oluşturan bir ürün var mı?', 0),
	(12, 'PLADIS', 'PLADIS_Q11', 'Gıda savunmasına aykırı şüpheli bir davranış/durum var mı?', 0),
	(13, 'PLADIS', 'PLADIS_Q12', 'Yüklenici firma için refakatçı belirlenmiş ve kontrolleri yapılmış mı?', 0),
	(14, 'PLADIS', 'PLADIS_Q13', 'İzinsiz fotoğraf ve video çekimi yapılıyor mu?', 0),
	(15, 'PLADIS', 'PLADIS_Q14', 'Çalışma yapacak kişinin sağlık raporu var', 0),
	(16, 'PLADIS', 'PLADIS_Q15', 'Çalışma yapacak kişinin İş Güvenliği Eğitimi var', 0),
	(17, 'PLADIS', 'PLADIS_Q16', 'Çalışanın iş için gerekli sertifikası var', 0),
	(18, 'PLADIS', 'PLADIS_Q17', 'Koruyucu ekipmanlar uygun', 0),
	(19, 'PLADIS', 'PLADIS_Q18', 'Kullanılacak makine ve aletler uygun', 0),
	(20, 'PLADIS', 'PLADIS_Q19', 'Çalışma alanı belirlendi', 0),
	(21, 'PLADIS', 'PLADIS_Q20', 'Yapılacak iş ile ilgili Alan Sorumlusuna bilgi verildi', 0),
	(22, 'PLADIS', 'PLADIS_Q21', 'Kullanılan aracın periyodik kontrolu var', 0),
	(23, 'PLADIS', 'PLADIS_Q22', 'Aracın güvenlik ekipmanları tam', 0),
	(24, 'PLADIS', 'PLADIS_Q23', 'Aracın durumu uygun', 0),
	(25, 'PLADIS', 'PLADIS_Q24', 'Gerekli ise sürekli gözetçi konuldu', 0),
	(26, 'PLADIS', 'PLADIS_Q25', 'Aydınlatma yeterli mi?', 0),
	(27, 'PLADIS', 'PLADIS_Q26', 'Nasıl çalışılması ve neler yapılması gerektiği anlatıldı mı?', 0),
	(28, 'PLADIS', 'PLADIS_Q27', 'Gözlemci acil durumda ne yapacağını biliyor mu?', 0),
	(29, 'PLADIS', 'PLADIS_Q28', 'Acil çıkış için tedbir alınması gerekiyor mu?', 0),
	(30, 'PLADIS', 'PLADIS_Q29', 'Tehlikeli kimyasalların atıksu arıtma tesisine gitmesi engellenmiş mi?', 0),
	(31, 'PLADIS', 'PLADIS_Q30', 'Çevre kirliliğine neden olabilecek katı ve sıvı atıklar ve gaz sızıntıları var mı?', 0),
	(32, 'PLADIS', 'PLADIS_Q31', 'Yapılacak çalışma esnasında çıkacak tüm atıklarla ilgili atık sorumlusuna bilgi verilmiş mi?', 0),
	(64, 'PLADIS', 'PLADIS_Q33', 'Yüksekte çalışacak kişilerin sağlık raporlarında Yüksekte Çalışabilir ibaresi bulunuyor mu?', 0),
	(65, 'PLADIS', 'PLADIS_Q34', 'Merdiven uygun mu?', 0),
	(66, 'PLADIS', 'PLADIS_Q35', 'Merdiven sabitlenmeli mi?', 0),
	(67, 'PLADIS', 'PLADIS_Q36', 'İskele uygun mu?', 0),
	(68, 'PLADIS', 'PLADIS_Q37', 'İskele duvara sabitlenmiş mi?', 0),
	(69, 'PLADIS', 'PLADIS_Q38', 'Yükselticiler uygun mu?', 0),
	(70, 'PLADIS', 'PLADIS_Q39', 'Yükselticilerin periyodik kontrolleri yapılmış mı?', 0),
	(71, 'PLADIS', 'PLADIS_Q40', 'Tekerlekli iskele veya yükselticilerin tekerlekleri kilitli mi?', 0),
	(72, 'PLADIS', 'PLADIS_Q41', 'Kişisel koruyucu donanımlar (emniyet kemeri, iş gözlüğü, baret, iş ayakkabısı... vb.) kullanılıyor mu?', 0),
	(73, 'PLADIS', 'PLADIS_Q42', 'Emniyet kemeri ve ona bağlı ekipmanlar uygun mu?', 0),
	(74, 'PLADIS', 'PLADIS_Q43', 'Emniyet kemerinin bağlanabileceği bir yer var mı?', 0),
	(75, 'PLADIS', 'PLADIS_Q44', 'Çalışma alanında uygun korkuluk var mı?', 0),
	(76, 'PLADIS', 'PLADIS_Q45', 'Çalışma yapılacak alan barikat veya şeritle çevrildi mi? Uyarı levhası asıldı mı?', 0),
	(77, 'PLADIS', 'PLADIS_Q46', 'Yukarıdan düşebilecek malzemeler sabitlendi mi?', 0),
	(78, 'PLADIS', 'PLADIS_Q47', 'Çalışılacak yerin alan sorumlusuna haber verildi mi?', 0),
	(79, 'PLADIS', 'PLADIS_Q48', 'Çalışma alanının altında çalışanlar uyarıldı mı?', 0),
	(81, 'PLADIS', 'PLADIS_Q50', 'Hava koşulları uygun mu?', 0),
	(95, 'PLADIS', 'PLADIS_Q52', 'Yüksekte askıda kalma durumu için acil durum planı biliniyor mu?', 0),
	(96, 'PLADIS', 'PLADIS_Q53', 'Ortam yanıcı maddelerden temizlendi mi?', 0),
	(97, 'PLADIS', 'PLADIS_Q54', 'Çalışma yapılacak alanın etrafı panellerle ayrılmış mı?', 0),
	(98, 'PLADIS', 'PLADIS_Q55', 'Alt veya üst katta yanıcı malzmemeler, izolasyon malzemesi vb. var mı?', 0),
	(99, 'PLADIS', 'PLADIS_Q56', 'Yanmaya maruz kalacak kişiler uzaklaştırıldı mı?', 0),
	(100, 'PLADIS', 'PLADIS_Q57', 'Yapılacak işe uygun yangın söndürücü var mı?', 0),
	(101, 'PLADIS', 'PLADIS_Q58', 'Kullanılan alet ve makineler uygun mu?', 0),
	(102, 'PLADIS', 'PLADIS_Q59', 'Elektrikli aletlerin kabloları sağlam mı?', 0),
	(103, 'PLADIS', 'PLADIS_Q60', 'Çalışılan yer makine ise, enerjisi kesildi mi?', 0),
	(104, 'PLADIS', 'PLADIS_Q61', 'Çalışılan yer makine ise, Kilitleme/etiketleme yapıldı mı?', 0),
	(105, 'PLADIS', 'PLADIS_Q62', 'Çalışma kapalı alanda ise havalandırma yeterli mi?', 0),
	(106, 'PLADIS', 'PLADIS_Q63', 'Yangın ihtimaline karşı ilave personel bulundurulmalı mı?', 0),
	(107, 'PLADIS', 'PLADIS_Q64', 'Kaynak, Kesim tüpleri, arabada ve sabitlenmiş mi?', 0),
	(108, 'PLADIS', 'PLADIS_Q65', 'Kaynak, Kesim tüplerinde gaz kaçağı var mı?', 0),
	(109, 'PLADIS', 'PLADIS_Q66', 'Aletlerin varsa; hortum, manometre ve vanaları sağlam mı?', 0),
	(110, 'PLADIS', 'PLADIS_Q67', 'Emniyet ventili, basınç düşürücü kontrolü yapıldı mı?', 0),
	(112, 'PLADIS', 'PLADIS_Q69', 'Kapalı alan en az 10 dakika havalandırıldı mı?', 0),
	(114, 'PLADIS', 'PLADIS_Q71', 'Alana girilmeden önce gaz testi yapıldı mı?', 0),
	(115, 'PLADIS', 'PLADIS_Q72', 'Ölçümü yapılan gaz oranları uygun mu?', 0),
	(116, 'PLADIS', 'PLADIS_Q73', 'İniş, çıkışta kullanılan merdiven vb. ekipmanlar uygun ve sağlam mı?', 0),
	(118, 'PLADIS', 'PLADIS_Q75', 'Kullanılacak elektrikli aletler ve kablolarının durumu uygun mu?', 0),
	(119, 'PLADIS', 'PLADIS_Q76', 'Çalışma yapılacak alana Etiketle/Kilitle uygulanmalı mı?', 0),
	(120, 'PLADIS', 'PLADIS_Q77', 'Kapalı alan dışında sürekli bir gözlemci bulunuyor mu?', 0),
	(121, 'PLADIS', 'PLADIS_Q78', 'Sürekli hava sirkülasyonu sağlanıyor mu?', 0),
	(122, 'PLADIS', 'PLADIS_Q79', 'Gaz değerlerinde sorun olduğunu bildiren uyarıcı cihaz bulunduruluyor mu?', 0),
	(123, 'PLADIS', 'PLADIS_Q80', 'Sürekli gaz ölçümü yapılıyor mu?', 0),
	(124, 'PLADIS', 'PLADIS_Q81', 'Yangın durumuna karşı uygun yangın söndürme ekipmanı bulunduruluyor mu?', 0),
	(129, 'PLADIS', 'PLADIS_Q86', 'Ortam sıcaklığı çalışma için uygun mu? Çalışma şartlarına göre gerekli molalar veriliyor mu?', 0),
	(130, 'PLADIS', 'PLADIS_Q87', 'Kapalı alanlarda kalma durumu için acil durum planı biliniyor mu?', 0),
	(142, 'PLADIS', 'PLADIS_Q88', 'Elektrik sisteme verilmeden önce elektrikten etkilenebilecek gruplar ve çalışanlara bilgi verilmiş mi ?', 0),
	(143, 'PLADIS', 'PLADIS_Q89', 'Panodaki çalışma başlamadan önce enerji kaynağından panoya gelen elektrik kesilmiş mi ? Panoda elektrik var mı?', 0),
	(144, 'PLADIS', 'PLADIS_Q90', 'Panoya gelen enerjinin kaynağı kesildiğine ve karşı tarafta çalışma yapıldığına dair etiketleme ve kilitleme yapılmış mı?', 0),
	(145, 'PLADIS', 'PLADIS_Q91', 'Bölgede yeterli uyarıcı ikaz işareti mevcut mu?', 0),
	(146, 'PLADIS', 'PLADIS_Q92', 'Elektriği sisteme veren çalışanda ve karşısındaki panoda çalışanda iletişim aracı mevcut mu?', 0),
	(147, 'PLADIS', 'PLADIS_Q93', 'Çalışanların yanlarında hazır işaretleme etiketleri var mı? Örnek: Elektrikle İlgili Çalışma Vardır, Dikkat Elektrik Var, Sisteme Enerji Verilmiştir gibi', 0),
	(148, 'PLADIS', 'PLADIS_Q94', 'Şalteri veya güç kaynağını kesen yada açan kişi bu konuda görevli olan kişi mi? Çalışanlar şalteri kimin açma ve kapatmaya yetkisi olduğunu biliyormu ?', 0),
	(149, 'PLADIS', 'PLADIS_Q95', 'YÜKSEK VOLTAJLA ile ilgili çalışma yapılan yerlerde, çalışanlar özel koruyucu ekipmanları giymişler mi? koruyucu kauçuk ayakkabı, kauçuk eldiven, anti statik kauçuk paspas, koruyucu elbise gibi', 0),
	(150, 'PLADIS', 'PLADIS_Q96', 'Tertip ve düzen sağlanmış mı ?', 0),
	(151, 'PLADIS', 'PLADIS_Q97', 'Yangın riskine karşı etraftaki yanıcı ve parlayıcı maddeler temizlenmiş mi?', 0),
	(152, 'PLADIS', 'PLADIS_Q98', 'Çalışma alanında yangın söndürücüler hazır bulunduruluyor mu?', 0),
	(153, 'PLADIS', 'PLADIS_Q99', 'Sisteme elektrik verildikten ve çalışma bittikten sonra çalışma alanı terkedilmeden önce elektrik verilen pano kilitleniyor mu ? panonun üzerinde kilit var mı?', 0),
	(154, 'PLADIS', 'PLADIS_Q100', 'Sisteme elektrik verildikten sonra elektrik verildiğine dair panoda işaretleme yapılıyor mu? Yapılmış mı ?', 0),
	(155, 'PLADIS', 'PLADIS_Q101', 'Çalışılan Panoda topraklama var mı? Saha elektrik tarafından yapıştırılmış, panoda topraklamanın olduğuna dair etiket ve imzalı kontrol logu panoda asılı mı ?', 0),
	(156, 'PLADIS', 'PLADIS_Q102', '1000 Volt ve üzerinde çalışma yapılacak ise EKAD belgesi var mı?', 0),
	(157, 'PLADIS', 'PLADIS_Q103', 'Yüksek gerilimde kalma durumu için acil durum planı biliniyor mu?', 0),
	(173, 'PLADIS', 'PLADIS_Q104', 'Güvenli giriş çıkış mevcut mu?', 0),
	(174, 'PLADIS', 'PLADIS_Q105', 'Bariyer ve uyarı işaretleri mevcut mu?', 0),
	(175, 'PLADIS', 'PLADIS_Q106', 'Hava durumu çalışmaya elverişli mi? Rüzgar hızı 35 km/sa\'ın altında mı?', 0),
	(176, 'PLADIS', 'PLADIS_Q107', 'Emniyet kemerleri sağlam ve kontrollü mü?', 0),
	(177, 'PLADIS', 'PLADIS_Q108', 'Yaşam hatları sağlam ve kontrollü mü?', 0),
	(178, 'PLADIS', 'PLADIS_Q109', 'Aydınlatma uygun mu?', 0),
	(179, 'PLADIS', 'PLADIS_Q110', 'Gerekli KKD kullanılıyor mu?', 0),
	(180, 'PLADIS', 'PLADIS_Q111', 'Çalışma alanı ıslaklığa sebep oluyor mu?', 0),
	(181, 'PLADIS', 'PLADIS_Q112', 'Kullanılan malzemeler düzenli bırakılıyor mu?', 0),
	(183, 'PLADIS', 'PLADIS_Q114', 'Çalışma alanı temiz bırakılıyor mu?', 0),
	(184, 'PLADIS', 'PLADIS_Q115', 'Tüm ekipmanlar kaldırıldı mı?', 0),
	(189, 'PLADIS', 'PLADIS_Q117', 'Sadece yetkili personel mi çalışıyor?', 0),
	(190, 'PLADIS', 'PLADIS_Q118', 'Yeraltı hatları belirlendi mi?', 0),
	(191, 'PLADIS', 'PLADIS_Q119', 'Saha trafiği kontrol altında mı?', 0),
	(192, 'PLADIS', 'PLADIS_Q120', 'Uyarı ikaz işaretleri mevcut mu?', 0),
	(193, 'PLADIS', 'PLADIS_Q121', 'Araç geri alarm sistemleri çalışıyor mu?', 0),
	(194, 'PLADIS', 'PLADIS_Q122', 'Uygun işaretler mevcut mu?', 0),
	(195, 'PLADIS', 'PLADIS_Q123', 'Çalışma alanı bariyerlendi mi ?', 0),
	(196, 'PLADIS', 'PLADIS_Q124', 'Gerekli KKD kullanılıyor mu ?', 0),
	(197, 'PLADIS', 'PLADIS_Q125', 'Kazı ekipmanlarının yük kontrol cihazı ?', 0),
	(198, 'PLADIS', 'PLADIS_Q126', 'Yağ sızıntısı önleme/kontrol mevcut mu ?', 0),
	(199, 'PLADIS', 'PLADIS_Q127', 'Kazı malzemesi kazıdan uzak depolanıyor mu ?', 0),
	(200, 'PLADIS', 'PLADIS_Q128', '1,2 metreden daha derin kazılarda şevlendirme yapılmış mı?', 0),
	(201, 'PLADIS', 'PLADIS_Q129', 'Kazı alanı temiz ve güvenli bırakıldı mı ?', 0),
	(203, 'PLADIS', 'PLADIS_Q130', 'Olası sızıntılar için emici ped var mı?', 0),
	(204, 'PLADIS', 'PLADIS_Q131', 'Alanda yangın olasılığına karşı yangın tüpü bulunduruluyr mu?', 0),
	(205, 'PLADIS', 'PLADIS_Q132', 'Kullanılan kimyasal için kimyasal maskesine ihtiyaç var mı? Evet ise maske var mı?', 0),
	(206, 'PLADIS', 'PLADIS_Q133', 'Uygun kişisel koruyucular sağlanmış mı? İş elbisesi, çizme, eldiven vb.', 0),
	(207, 'PLADIS', 'PLADIS_Q134', 'Kullanılan kimyasalın malzeme bilgi güvenlik formu bulunduruluyor mu?', 0),
	(208, 'PLADIS', 'PLADIS_Q135', 'Malzeme bilgi güvenlik formnuna göre çalışanlar tehlike konusunda bilgilendirilmiş mi?', 0),
	(209, 'PLADIS', 'PLADIS_Q136', 'Alanda göz ve boy duşu bulunduruluyor mu? Malzeme bilgi güvenliğine göre uygun ise.', 0),
	(210, 'PLADIS', 'PLADIS_Q137', 'Kimyasallar taşma kabı içerisinde muhafaza edilmiş mi?', 0),
	(211, 'PLADIS', 'PLADIS_Q138', 'Kimyasallar taşınırken dökülmeye karşı önlemler alınmış mı?', 0),
	(212, 'PLADIS', 'PLADIS_Q139', 'Kimyasallar depolama matrisine göre mi depolanmış?', 0),
	(213, 'PLADIS', 'PLADIS_Q140', 'Statik elektriğe karşı önlem alınmış mı? (bakır levhası)', 0),
	(214, 'PLADIS', 'PLADIS_Q141', 'Gıda Güvenliğini/ürün kalitesini riske atacak durumlar/davranışlar için aksiyonlar alınmış mı?', 0),
	(215, 'PLADIS', 'PLADIS_Q142', 'Çalışma sonunda üretim alanına doğrudan temas edecek tüm açıklıklar kapatıldı mı? ', 0),
	(216, 'PLADIS', 'PLADIS_Q143', 'Çalışma sonunda ürüne yabancı madde bulaşma riski oluşturacak malzemeler uzaklaştırılmış mı?', 0),
	(217, 'PLADIS', 'PLADIS_Q144', 'Çalışma yapılan alandaki tüm pest kontrol ekipmanları yerinde ve çalışır durumda mı?', 0),
	(218, 'PLADIS', 'PLADIS_Q145', 'İş bitiminde çalışma alanı iş kazası, yangın vb. sebebiyet vermeyecek şekilde düzenli bırakılmış mı?', 0),
	(219, 'PLADIS', 'PLADIS_Q146', 'İş ekipmanları güvenli bir şekilde bırakılmış mı, emniyete alınmış mı? (Enerjisi kapatılmış, sabitlenmiş, vb.)', 0),
	(220, 'PLADIS', 'PLADIS_Q147', 'Yapılan proje/çalışma alanı yeni bir risk oluşturarak, iş kazasına veya tehlikeli duruma sebep olabilir mi?', 0),
	(221, 'PLADIS', 'PLADIS_Q148', 'Yapılan proje/çalışma herhangi bir ekipmana, demirbaş malzemeye zarar vermeden tamamlanmış mı?', 0),
	(222, 'PLADIS', 'PLADIS_Q149', 'Çalışma sonunda çıkan atıklar (tehlikeli atık, ambalaj vb.) uygun bertaraf edilmiş mi?', 0),
	(223, 'PLADIS', 'PLADIS_Q150', 'Enerji kaynakları kullanılmıyorsa kapatılmış mı?', 0),
	(224, 'PLADIS', 'PLADIS_Q151', 'Gıda Güvenliği kurallarına uygun çalışılyor mu? ', 0),
	(225, 'PLADIS', 'PLADIS_Q152', 'Çalışma yapılan alan düzenli mi? ', 0),
	(226, 'PLADIS', 'PLADIS_Q153', 'Üretim sahası kurallarına uygun hareket ediliyor mu? (yeme/içme, el dezenfeksiyonu, kişisel koruyıcı donanım vb.) ', 0),
	(227, 'PLADIS', 'PLADIS_Q154', 'Çalışma alanında ürünlere kontaminasyon (fiziksel, kimyasal, biyolojik, radyolojik alerjen, helal) riskine karşı önlem alınmış mı? ', 0),
	(228, 'PLADIS', 'PLADIS_Q155', 'Kullanılan kimyasallar iş başında onaylanan kimyasallar mıdır? ', 0),
	(229, 'PLADIS', 'PLADIS_Q156', 'Çalışanlar İSG kurallarına uygun çalışıyor mu?', 0),
	(230, 'PLADIS', 'PLADIS_Q157', 'Çalışan İSG kurallarına uygun KKD kullanıyor mu?', 0),
	(231, 'PLADIS', 'PLADIS_Q158', 'Çalışan iş ekipmanlarını İSG kurallarına uygun kullanıyor mu?(Kabloda açıklık, muhafazası sökülen ekipman vb.)', 0),
	(232, 'PLADIS', 'PLADIS_Q159', 'İş kazası, tehlikeli durum, yangın vb. oluşma ihtimali var mı?', 0),
	(233, 'PLADIS', 'PLADIS_Q160', 'Çevreye zarar verebilecek maddeler (kimyasal boya, tehlikeli atık vb.) uygun şartlarda muhafaza ediliyor mu?', 0);
/*!40000 ALTER TABLE `work_permit_question` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
