# Kaynak Adres: https://geshan.com.np/blog/2022/02/mysql-docker-compose/
#Kodu calıstırmak icin: 
   #mssql için: sqlcmd -S localhost,1433 -U SA -P "YourStrong@Passw0rd" -i /docker-entrypoint-initdb.d/your-script.sql

version: '3.8'
services:
  myServiceMysql:
    image: mysql:8.3.0
    container_name: "mysql"
    command: 
      - 'mysqld'
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    #command: sh -c "echo './create-scripts' && sleep 5 && echo './insert-scripts'"
    cap_add:
      - SYS_NICE # Bazı hata mesajlarını bastırma
    restart: always # Docker Compose başarısız olması durumunda bu konteyneri her zaman yeniden başlat
    environment:
      - MYSQL_DATABASE=mysql-db
      - MYSQL_ROOT_PASSWORD=root # Bu bir örnek parola, güvenlik için daha güçlü bir parola kullanın
      # - MYSQL_USER=dbuser # Kullanıcıya yetki vermek için kullanılır
      # - MYSQL_PASSWORD=secret
      #- MYSQL_ROOT_HOST=127.0.0.1

    ports:
      - '3333:3306'

    volumes:
      #- mysql:/var/lib/mysql
      #- mysql-data:/var/lib/mysql #çalışmadı
      # Localde bulunan 'create-scripts' klasörünü Docker'daki '/docker-entrypoint-initdb.d' klasörüne bağla
      # Bu, Docker ilk çalıştığında eşitleme yapar
      - './create-scripts:/docker-entrypoint-initdb.d'
      #- './create-scripts:/docker-entrypoint-initdb.d/create-scripts'
      - './insert-scripts:/docker-entrypoint-initdb.d/insert-scripts'
    networks:
      - mynetwork
      # mysql_network:
      #   ipv4_address: 172.1.1.1  

  myapi:
    image: webapplication2
    container_name: "webapplication2"
    build:
       context: .
       dockerfile: C:/Users/DDK-01/source/repos/WebApplication2/WebApplication2/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      #ConnectionStrings__DefaultConnection: "Server=myServiceMysql;Port=3333;Database=mysql-db;User=root;Password=root;Convert Zero Datetime=True;"
      ConnectionStrings__DefaultConnection: "Server=127.0.0.1;Port=3333;Database=mysql-db;User=root;Password=root;Convert Zero Datetime=True;"
    ports:
      - '80:80'
    depends_on:
      - myServiceMysql
    networks:
      - mynetwork 
    volumes:
      #- './ada/schema.sql:/docker-entrypoint-initdb.d/schema.sql'
      - './schema.sql:/docker-entrypoint-initdb.d'

 
  #frontend:
  #  build: ./WebApplication2
  #  container_name: "frontend"
  #  port: "8000:8000"
  #  depends_on:
  #    - mysql
  #  networks:
  #    - mynetwork





volumes:
  mysql_data:
    driver: local
    # - db:/var/lib/mysql
    # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  #mssql_data:
  # driver: local
  #  #- mssql_data:/var/opt/mssql
  #postgres_data:
  # driver: local
  #  #- postgres_data:/var/lib/postgresql/data
networks:
  mynetwork:
    driver: bridge
    #external: true